steps:
  - label: Lint
    plugins:
      - plugin-linter#v2.0.0:
          id: forumone/capistrano

  - label: Shellcheck
    plugins:
      - shellcheck#v1.1.2:
          files:
            - hooks/**
            - tests/**/*.bash

  - label: Tests
    plugins:
      - docker-compose#v3.0.0:
          run: tests
